{% set name = "psi4" %}
{% set version = "1.10a2" %}
{% set commit = "c76fd5885" %}
{% set sha256 = "d70ee00da3fe53f0caa0f4e3d89fc52a9999f04c266a23ff5c9fca338baa6245" %}

# versioning: want conda package and `psi4 --version` to match
# * proper tagged releases compute their versions consistent with recipe w/o interventions.
#   so comment out the "echo ... metadata.py" cmds in build.sh and bld.bat. ("commit" var here also disposable.)
# * to package _any_ commit, set it to "commit" jinja, set "version" jinja to a fake prerelease tag like "1.8a3", use the "commit" version for source/url, edit the sha256, and let the "echo ... metadata.py" machinery work.
#   note that the non-c-f recipe didn't need this machinery b/c it used source/git_url and load_setup_py_data.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/{{ name }}/{{ name }}/archive/{{ commit }}.tar.gz
  url: https://github.com/loriab/{{ name }}/archive/{{ commit }}.tar.gz
  #url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
#  patches:
#    - 0001-allow-libxc-7.patch
  sha256: {{ sha256 }}

build:
  number: 10
  #skip: true    # [ppc64le]
  skip: true  # [ppc64le or py != 312]
  script_env:
    - PSI4_PRETEND_VERSIONLONG={{ version }}+{{ commit }}
  binary_relocation: true
  run_exports:
    # only relevant for the rare "psi4 plugin" case (links to psi4/core.*so), not the usual "psi4 module" case (import psi4)
    - {{ pin_subpackage('psi4', max_pin='x.x') }}
  ignore_run_exports_from:
    - zlib

# bkgd: the numpy story
# * psi4 uses numpy at runtime and has no version constraints
# * it should be around at compile-time for `find_package(Python ... NumPy)`
# * this doesn't need to be explicit for most arch but does for osx-arm64 for cross-compile
# * to avoid false numpy matrix, add it to ignore_run_exports

# bkgd: the fortran story
# * psi4 has no fortran code and no fortran required dependencies (besides blas/lapack)
# * it does have optional functionality-expanding fortran dependencies like dkh (recipe alongside) that are packaged separately
# * this recipe omits the fortran compiler since C++ compiler can do the linking and because on windows,
#   the clang-cl + gfortran combination hits https://gitlab.kitware.com/cmake/cmake/-/issues/17810

# bkgd: the general blas story
# * psi4's performance is heavily dependent on the blas/lapack implementation
# * we've been packaging on conda with mkl for the past 7y
# * while the psi4 build system allows any blas impl, we emit "untested" warnings for non-MKL, and the last test of openblas 5y ago had threading oversubscriptions
# * so while we're open to multiple impl in future and have been specifying generic "libblas" in deps like dkh, we'd like to support only mkl in psi4 for now

# bkgd: the windows blas story
# * the latest blas+win+mkl package (libblas-3.9.0-16_win64_mkl) depends on mkl=2022.1.0, even though mkl=2022.2 and 2023.0 are available.
# * so the `{{ mkl }}  # [win]` below pins to 2022.1.0 so that libblas=*=*mkl can work correctly to set the blas implementation.
# * without the `{{ mkl }}` pin, various attempts would either install mkl + openblas + libblas=*=*openblas or try to fall back to libblas==3.8.0=10_mkl
# * current conda-forge-pinning is mkl=mkl-devel=2022, so hopefully this recipe is still consistent with the c-f stack.
# * [Oct 2023, #19] new libblas w/mkl2023 available for all arch, so releasing pin and consolidating lines
# * [Jul 2024] removing the cbc.yaml now that mkl2023 is universal. also can use adcc again

# bkgd: the windows openmp story
# * the windows mkl package depends on intel-openmp (provides libiomp5md.dll).
# * llvm-openmp is another contender on windows (provides libomp.dll=libiomp5md.dll and assoc. import libs libomp.lib=libiomp5md.lib).
# * intel-openmp libiomp5md.dll is twice the size of the llvm-openmp file of the same name, and there's reports of non-interchangeability:
#   * https://github.com/conda-forge/conda-forge.github.io/issues/1597#issuecomment-1029224521
#   * https://github.com/conda-forge/intel_repack-feedstock/issues/1#issuecomment-579975070
# * so we'd like to keep depending on intel-openmp, but since the package only provides the runtime dll,
#   not the buildtime import lib, we stash a copy of the latter in a repo (see 2nd source/url above)
#   for compiling psi4. It is used at buildtime and never packaged.
# * for threading on windows, we're certainly willing for the psi4 recipe to do whatever works well with the c-f stack.
#   However, at the moment this aspect of the stack seems a little fractured, so the recipe is defaulting to the
#   mkl + intel-openmp + stashed libiomp5md.lib procedure that has worked compatibly with c-f for the last couple years.
# * [Jul 2024] intel-openmp now provides libiomp5md.lib so dropping the external src.

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - qcelemental                            # [build_platform != target_platform]  # version detection w/cross+poetry
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - llvm-openmp                            # [unix]
    - intel-openmp                           # [win]
  host:
    - setuptools                                       # qcelemental detection
    - eigen
    - libboost-headers
    - libblas * *mkl                         # [x86_64]
    - mkl-devel                              # [x86_64]
    - intel-openmp                           # [win]
    - mkl                                    # [x86_64]
    - libblas * *netlib                      # [not x86_64]
    - liblapack * *netlib                    # [not x86_64]
    - numpy
    - pybind11
    - pybind11-abi
    - python
    - zlib                                             # pcmsolver detection, not direct dep, so ignore_run_exports above
      #- pip                                           # internal builds of python modules, so usually off
    # qc req'd
    - gau2grid
    - libint 2.9.0
    - libxc-c
    - optking
    - qcelemental
    - qcengine
    # qc opt'l, build-time
    - dkh
    - libecpint
    - pcmsolver
  run:
    - llvm-openmp                            # [unix]
    - {{ pin_compatible('intel-openmp', max_pin='x.x') }}  # [win]  # avert 2024.2.2
    - libblas * *mkl                         # [x86_64]
    - mkl                                    # [x86_64 and not win]
    - {{ pin_compatible('mkl', max_pin='x.x') }}  # [x86_64 and win]  # avert 2024.2.2
    - libblas                                # [not x86_64]
    - liblapack                              # [not x86_64]
    - msgpack-python
    - networkx
    - pydantic >=1.10
    - python
    - scipy
    - {{ pin_compatible('numpy') }}          # shouldn't be needed but last round had constraint >=1.19,<3 so allowed v1 np in a v2 psi4 build on win
    # qc
    - {{ pin_compatible('optking', max_pin='x') }}
    - {{ pin_compatible('qcelemental', max_pin='x') }}
    - {{ pin_compatible('qcengine', max_pin='x') }}
  run_constrained:
    - pytest >=7.0.1
    # qc opt'l, run-time
    - pylibefp ==0.6.2                                 # 0.6.2 provides windows arch
    - dftd4-python >=3.5.0                             # 3.5.0 provides b97-3c parameters
    - geometric >=1.0                                  # 1.0 has new API
    - pymdi >=1.2                                      # 1.2 has breaking API change
    - pyddx >=0.4.3                                    # 0.4.3 has lpb correction
    - adcc >=0.15.16                                   # 0.15.16 has transition moment corrections
    # - cppe ==0.3.1                                   # 0.3.2 has libecpint problems

test:
  imports:
    - psi4
  requires:
    - pip                                                                          # provides `pip check`
    - pytest
    - pytest-xdist
    # qc runtime opt'l
    - adcc                                                               # [unix and not ppc64le]
    - cppe                                                               # [unix]  # win uses llvm-openmp
    - pyddx                                                              # [unix]
    - dftd3-python
    - dftd4-python
    - toml                                                                         # needed for qcengine/dftd4-python interface
    - pylibefp
    - gcp-correction
    - geometric
    - pygdma
    - pymdi
    # plugin testing
    - {{ compiler('cxx') }}                                              # [unix and build_platform == target_platform]
    - cmake                                                              # [unix and build_platform == target_platform]
    - make                                                               # [unix and build_platform == target_platform]
    - pybind11                                                           # [unix and build_platform == target_platform]
    - eigen                                                              # [unix and build_platform == target_platform]
    - libboost-headers                                                   # [unix and build_platform == target_platform]
  commands:
    # Verify module
    - test -f $SP_DIR/psi4/core*.so                                      # [unix]
    - test -f $SP_DIR/psi4/driver/driver.py                              # [unix]
    - if not exist %SP_DIR%\\psi4\\core*.pyd exit 1                      # [win]
    - if not exist %SP_DIR%\\psi4\\driver\\driver.py exit 1              # [win]
    # Verify executable
    - test -f $PREFIX/bin/psi4                                           # [unix]
    - psi4 --version                                                     # [unix]
    - psi4 --module                                                      # [unix]
    - if exist %PREFIX%\\Scripts\\psi4 exit 1                            # [win]
    - if not exist %PREFIX%\\Scripts\\psi4-script.py exit 1              # [win]   # aka bin/psi4
    - if not exist %PREFIX%\\Scripts\\psi4.exe exit 1                    # [win]
    - psi4.exe --version                                                 # [win]
    - psi4.exe --module                                                  # [win]
    - python -c "import psi4;print(psi4.executable)"
    # Verify accessories
    - test -f $PREFIX/include/psi4/psi4-dec.h                            # [unix]
    - test -f $PREFIX/share/cmake/psi4/psi4Config.cmake                  # [unix]
    - test -f $PREFIX/share/cmake/TargetLAPACK/TargetLAPACKConfig.cmake  # [unix]
    - test -f $PREFIX/share/psi4/basis/cc-pvdz.gbs                       # [unix]
    - if not exist %PREFIX%\\Library\\include\\psi4\\psi4-dec.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\psi4\\psi4Config.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\TargetLAPACK\\TargetLAPACKConfig.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\psi4\\basis\\cc-pvdz.gbs exit 1  # [win]
    # Inspect linkage
    - ldd -v $SP_DIR/psi4/core*.so                                       # [linux and build_platform == target_platform]
    - otool -L $SP_DIR/psi4/core*.so                                     # [osx]
      # LONG - '%OBJDUMP% %SP_DIR%\\psi4\\core.*.pyd | findstr /i "dll"' # [win]
    # Actually test
    # - pip check                                                        # present until poetry killed off in qcel
    - python -c "import psi4;assert psi4.__version__ == '{{ version }}', f'{psi4.__version__=} differs from recipe=\'{{ version }}\''"
    - python -c "from psi4 import core; core.set_num_threads(42); assert core.get_num_threads() == 42"
    - python -c "import psi4;print(psi4.addons())"
    - psi4 $SP_DIR/psi4/tests/tu1-h2o-energy/input.dat -o stdout         # [unix]
    - psi4 %SP_DIR%\\psi4\\tests\\tu1-h2o-energy\\input.dat -o stdout    # [win]
    - MKL_CBWR=AVX pytest -rws -v --durations=20 --color yes -n auto $SP_DIR/psi4 -m "smoke" -k "not pe_ecp"  # [unix and build_platform == target_platform]
    - MKL_CBWR=AVX pytest -rws -v --durations=20 --color yes -n auto $SP_DIR/psi4 -k "adcc and not pvdz_adc2_any_6"  # [unix and build_platform == target_platform]
    - pytest -rws -v --durations=20 --color yes -n auto $SP_DIR/psi4 -k "psi4_basic"  # [unix and build_platform != target_platform]
    - pytest -rws -v --durations=20 --color yes -n auto %SP_DIR%\\psi4 -m "smoke and not d2ints" -k "not pe_ecp and not cc13"  # [win]
      # cn_cc-pvdz_adc2_any_6 only trouble for py39 + osx-64
      # emulated aarch64 passes usual smoke+adcc tests but takes 2h, so skipping longest
    # Test a plugin
    - PLUG=plugdfmp2                                                     # [unix and build_platform == target_platform]
    - psi4 --plugin-name $PLUG --plugin-template dfmp2                   # [unix and build_platform == target_platform]
    - cd $PLUG && `psi4 --plugin-compile` && make && cd ..               # [unix and build_platform == target_platform]
    - PYTHONPATH=. python $PREFIX/share/psi4/scripts/test_threading.py --plugin-dfmp2 --module="$PLUG" -n2  # [unix and build_platform == target_platform]
    - PYTHONPATH=. python $PREFIX/share/psi4/scripts/test_threading.py --passfail --ldd --module="$PLUG/$PLUG"  # [unix and build_platform == target_platform]

about:
  home: http://psicode.org
  dev_url: https://github.com/psi4/psi4
  doc_url: http://psicode.org/psi4manual/master/index.html
  doc_source_url: https://github.com/psi4/psi4/tree/master/doc/sphinxman/source
  license: LGPL-3.0-only AND BSD-3-Clause AND MIT
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - COPYING
    - COPYING.LESSER
    - THIRD-PARTY-LICENSES
  license_family: LGPL
  summary: Open-Source Quantum Chemistry - an electronic structure package in C++ driven by Python
  description: |
    Psi4 is an open-source suite of ab initio quantum chemistry programs designed for efficient,
    high-accuracy simulations of a variety of molecular properties. We can routinely perform computations
    with more than 2500 basis functions running serially or on multi-core machines. With computationally
    demanding portions written in C++, Pybind11 exports many of the C++ classes into Python, and a
    flexible Python driver, Psi4 strives to be friendly to both users and developers.

extra:
  recipe-maintainers:
    - loriab
    - jturney
    - fevangelista
    - maxscheurer


# Notes
# -----

# * The following optional runtime deps were in req/run of the psi4::psi4 package but are omitted from conda-forge::psi4
#   * pytest
#   * dftd3
#   * gcp
#   * dftd4 (installer only)
